// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaW1fjuLL+K1o68wBncoOmL5PzMCsd0nRWQ8iBwDl7NWyWYlcSDbLklmQg0+S/76WL",
	"HTu20zC7h8XDfotlXUpVX1V9Vc53HIgoFhy4Vrj7HcdEkgg0SPt0KVgSwTAcE70wzyGoQNJYU8FxFx/2",
	"TxDlShMeABoeop0wiJrpQJOGiJEpsF3cwNRMj80mDcxJBLiL7+zWNzTEDSzhW0IlhLirZQINrIIFRMQc",
	"OBMyIhp3cZLYmXoZm8VKS8rneLVapZOtuAMphSzLefapj95/6LxH5qqMEq4RmJlIgooFV4AbOJYiBqkp",
	"KLdeE8rKO31OIsKbEkhIpgwQPMSMcGJeIhVDQGc0QFogvaAKiSBIpAQeQFluoxGnpvIZF5x+SwDRELim",
	"MwoSzYR0WzqpCxuvFSRpU8IMak9UmuhEVdxpMhkj9xIFIixsSrl+s7/ejHINc5BmN001qxD+fCGkRoui",
	"mlQSRUQuq4RyA5u7WDsi8y6VCHgS4e5XPBxd9o6Hhze9s6OLk8Foght4dDq5+XR6MTrEDdw7Phv0Dv9x",
	"M/j/4fnkHDfweHB2Mjw/H56Obg4Ho+HATLoY9S4mnwejybDfm9iR4WgyOBv1jt3Ly97wuPfxeIAb+FNv",
	"eDw4vBmfDfqno8PhZHg6wtdPV/oqD+2v7m2quutstpj+AYE22vgMhFU5mhtPjaQonzPQghv8ikQGZfzG",
	"lf7aJ1xwGhCGzHskZkgvIL8JPJAoNmbFCyeJkZ+Ep5wtU9d8OqzyMlfs/Qw4nHkJHSLWjlHY9faDaiot",
	"JJlDU4G8owE0YynuaAiyFQZRi4p2dqtaA/7wukmsaVQFfAgED61xjKALQF4IlAphVCE1hHmp37zrdGoP",
	"zXnbHUhlzykfu3HINKEsROn8vIL2Wp1W58dXrMZsZkYfxNcHeIWU4NzAD00CcTODl4OlBsmV2djb4rqB",
	"Y5ZIwjJgmFMyiGcZgfJ5wojMQ9Of9wzDm8t9SaYgOWhQYz/pM/W5j4QhNXolbJzzphlhChobel/v0swC",
	"//iyjxRoTflclTySBAEodROZcNb9jn+RMMNd/F/tdfZt+0TWdkm3ZxecmPnWy+wFbwJGVIWznbvXffMW",
	"mQSLdsQdSElDUOh8jEKYkYTp3Sqf84n46ZI5mVYV8euJGnUmLd4gXbpW58JsgmZSRNadAqIJE/OSYm8z",
	"S/xI+jrLV17Fa/Q8hqBW3VnOdwzApOlAAjEAQMTCYYca54uMGPYSsZDapcR0B++/5vzd0t0CEpOA6mVV",
	"SPyWgNIQZjulc9EOtOatBrrCe53OEb3Cu8UoYAadHxtXxF38z6+d5m/Xv+5cXbXcr93fdwb0cUwfJ/Tx",
	"iD6e0Mcv9HHwOH6cPB49njx+2f39lyocRaBJSDR5IojS2St7aWuOm0WKm23rN4zXwF6HN9XJ4zyn4Typ",
	"2okSpdEU0FXqXF5Vnmn4wVxgq4mQheNzamiszXe9BWA16bNvKZ5Oc77P1amxM9a902ciCQd3FmExWTJB",
	"QpQoUJ4w8iTKX2p8dno5NGxoODrCDXx2MfK/HNHBDXw4OB5M3Jj9OTis0EDDFwZlsd14ximQhFiCMkrP",
	"fCJjviW0G9+Bm+r8OqERKE2iGN0vgFtluMCF7olybmdTa5bZQ6Khafd6Qlan4b9T3WwWKT88rpqeZTTH",
	"srMamuMurdp7+2/g4O2790348Nu0ubcfvmmSg7fvmgf7797tHey9P+h0Ok+ibz7AbfO4fCwsMD7C2OkM",
	"d78+bblbtrrelMqyqvCvmp4RpZFb/1ftv+nQ5p7P5jOpYb5nhe2qQG78e1zgMm7weVzGr1llXphjCiXd",
	"GYdz1AOZBN9CfcG1FEwhojUJFpGNMYGIAREeohhkRJVhdmaCz2aCX3GjSLRTwXr+BykopjFDNii3aV/t",
	"tq54LvycAQn/T1INp87/z7xdTghf+kf72j5f52G/ubImIB1TpSuUQOaUG3wgRpU2sdTjJ/XmMl3j8KBv",
	"YsO4tLiFCuI9McM25UvQksKdCXAGmmYlMivNORJUwrSqp132MKohUk9Lm+siCRMpybKavGyk2PpIkyYr",
	"e5E04jg6U1KJDXdbWN338h03U5rSIkK3sGzeEZaYOEelct0NMp/bDMFDNKNMg92h4maueVSFcst6qQsP",
	"geAzOk8khHZYxcSCJiIPx8DnJva+e9PAEeXp416REJHmn4YJ7Xxt+l//nQ7VcJ/1KSXZ1j6zlsUEMumq",
	"RCN6MYM9oeJ+Zi0wFQkPXV/KHviUQ3wUq9b3R7vh2NSASgPXPuvbw2yMJneEMkN0nx187YHX9ZiujXLe",
	"paNiv+gTZaCWSkOEG/gjE8HtFjpzYbNILalxSSZjWTsZ44aHmHATNJHgbGlAeLf3HDI/gvsKGp/y07lF",
	"hkR6QThynT9d5PT7fxOn3zDNFjq7sh3NmbD3FFyTwIZh3+o1TGoshU+jibS1vtax6rbbc6oXybQViKht",
	"+FXsprW3JcJyZDkbnE9Qbzy0sSQinNhgEmf4zLTrgy7a2cRunxEaqd0rLjjKeWzAEqVBKiQ4msKCsJmJ",
	"6of9k9YVnxiC7Q5lTNwr1BvYPioPiQxdWAsEd6cES0QCKZQya9NsqVxyZDQAriCnr15MggWgfduuKarr",
	"/v6+RezrlpDztl+r2sfD/mB0PmjutzqthY5YrkWbj0Bp4ZoWRWktZe6R6+qkzaJVA4sYOIkp7uI3rU7r",
	"wHeALKDbJKbtuz3C4gXZS1ss3e94Droq5dgs6YLeotDPdO1tQF8+5AQce5GMB9l8NAxxFx+B/rzuTLrm",
	"vZVlv9NJsQfcHk/imPlU1v5Dud7Z+rvCtkz7OW0WlXBW7MP6xG9q8MRSrFnC2NIo7e1WaWIppgyiX58n",
	"lfu2USHUkBunJ8zCCqT7SGCdN+27W72hTHGazC1j9QPXZmrRljluUmlMQ7MQYWzDr9Z8Ct1TvTAsiKZf",
	"R5I4FlKXDGp2usyYcf7j09fNQ0/IA42SCPEkmoL07MrSGGVc3XKu9FPTtwTs9wbvUBF5cGRO0T9tNzPT",
	"uG+M4e7bTsVnj8gdibt7nU7HEgb/WO7Rrhr1DHELLaySNkc786JuBufrv9EFcmy6AnHeYFsc4OBlHeCO",
	"MBoi6XpiKIei1+iL1nnWmE+9MR25XjVwLKrKmL4lAoggnuMLG55Xk9l2S47nNrtM68+tnlfqhFxcDA93",
	"W+gIuNkSQkRnSERUawhbNaC2jZGnf9e9dtQDlP4owuVPw3Whk1HkN74TseFSez/ZperdKa0AXpsvWbLr",
	"5Pjt5eSwZZHJIYqkhQVhppIwbJsq1/g92N9/OYnWHfdCgRUKU9gJ7cR6lQHHx43M18sRp44AFJpZNh4x",
	"qCqQDu04Ius/QZTD0mW/HITcurogVKWQ9ZR24b8pFdnwoLaQc9eo8rSDl7NcWjMLjWamnH6V0PGG3QKd",
	"xg/o/hZMTJdoI7NU8f2/CR2dlwvs22jSfwBXLlS2oi0mOqj4duJaNwZtBV7UQnd7ae2hUE3DplWCndvt",
	"5yHv5xOZQsPqSUzmBQHvG2X2I8DroTTrzppaSMpvKZ9bZ/DwgHD3Vbjki9KsHko/BfxvIjRBjEbUfqr1",
	"mFWt9Rfn2s46uhcJC9EUEDwEACGEL07OqikZYUzcp2kn8/lXGfd8/NrG0fw/HapLtELvbKO5lzUR2zYc",
	"+a1r/q8XLCC4RVk4VOsKLm2LNWpYFaMzCJYBA9eBtf96qdwovdPqevWvAAAA//9fxAChfiwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
