// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.1-0.20260318123712-00a90b7a03f4 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xaXXPbttL+Kxi8vbDfUh920rTVuegoEuNoYssaWfE5ZyIfD0SuJDQgwACgbTXWfz+D",
	"D1KUSMl2p8n04tyJILBYLHaffXaprzgSSSo4cK1w5ytOiSQJaJD26VqwLIFBPCJ6aZ5jUJGkqaaC4w7u",
	"9y4Q5UoTHgEa9NFRHCWNfKBBY8TIDNgxDjA8kCRlgDuYpGkjJpo07qxoHGBqRKVmgwBzkphJ7t0tjXGA",
	"JXzJqIQYd7TMIMAqWkJCnKpagzSr//OJNP5oN369OfI/Gjdf28Gbk3U+fvzbDzjAepUa6UpLyhd4vV7n",
	"0uxZQymFrB5y/K6Hfv6l/TMydmKUcI3AzEQSVCq4MkdIpUhBagrKrdeEsqqk91lCeEMCicmMAYKHlBFO",
	"zEukUojonEZIC6SXVCERRZmUwCOo6m1M5mxc3eMjp18yQDQGrumcgkRzIZ1Ip/WW4LmQCdG4gzNJGxLm",
	"sHdHpYnOVM2ZJpMRci9RJOItoZTrV6cbYZRrWIA00jTVrEb5q6WQGi23zaSyJCFyVaeUG9iVYu8RmXe5",
	"RsCzBHc+4cHwuns+6N92x2cfL8LhBAd4eDm5fXf5cdjHAe6ej8Nu/9+34b8GV5MrHOBROL4YXF0NLoe3",
	"/XA4CM2kj8Pux8n7cDgZ9LoTOzIYTsLxsHvuXl53B+fdt+chDvC77uA87N+OxmHvctgfTAaXQ3zzfKOv",
	"y77/yb3NTXdTzBaz3yHSxhrvgbC6KHXj+SUpyhcMtODGf0Umo6r/prXB3iNccBoRhsx7JOZIL6EsZBPj",
	"S6eJ0Z/El5yt8th9vluVda6R/QJ3GHsNnUdsAmNL6udfVENpIckCGgrkHY2gkUpxR2OQzThKmlS0ilPt",
	"vcAnj5ulmiZ1jg+R4LG9HKPoEpBXAuVKGFNIDXFZ61dv2u29m5ai7Q6ksvtUt93ZZJZRFqN8ftlAJ812",
	"s/30Eet9trhGj/KbDbxBKu4c4IcGgbRRuNcG7pUR7O/iJsApyyRhhWOYXQoXL1IG5YuMEVl2Tb/fCy7e",
	"HO5DNgPJQYMa+UnvqU+cJI6psStho1I0zQlTEOzYfSOlUQD/6LqHFGhN+UJVIpJEESh1mxg463zFP0iY",
	"4w7+v9Ymdbd8Imu5jN21Cy7MfBtl9oC3ESOqJtiu3OueeYtMBkZH4g6kpDEodDVCMcxJxvRxXcz5TP18",
	"zZxO6xr8eqZF3ZVunyBfujHn0ghBcykSG04R0YSJRcWwn4ubeEr7fTdfexRv0asUor3mLnK+YwAmTUcS",
	"iHEARKw7HFETfIlRwx4iFVK7lJhL8PFr9j+unC0iKYmoXtVB4pcMlIa4kJTPRUfQXDQDNMUn7fYZneJt",
	"8mYHXRwXzMvQqx+PptOm+3X821FIH0f0cUIfz+jjBX38QB/Dx9Hj5PHs8eLxQy0TC3ACmhha+Ewnymev",
	"7aHtddwuc785tH7n8gLsbXhbnzyuShYuk6qjJFMazQBN8+DypvJMww+WgG0PQm5tXzJDsLm+mwMOtid9",
	"9izF03nO97k6v+yCsh/1mMji8M56WEpWTJAYZQqUJ4w8S8qHGo0vrweGDQ2GZzjA449D/8sRHRzgfnge",
	"TtyY/Rn2aywQ+KqiqrYbLzgFkpBKUMboRUwUzLfi7SZ24LY+v05oAkqTJEX3S+DWGA640D1RLuxsai0y",
	"e0w0NKysZ2R1Gn+r0ighD+fAF4aOvXkV4ITy/PEkeHn58+RB6olfQaAs79tDoJzKqlU9w9Mc0KPkobAt",
	"A+oWbSSMXc5x59Pzlrtl65tdrSw1i/+s/zCiNHLr/6wT7aKCOeeLSVF+B1+L8nm9xZD8e7xFiIp7egEh",
	"8mvWRSiX6EbFdiZqHX9BhiU0UU9wLQVTiGhNomVigSoSKSDCY5SCTKgy9NBM8ClR8Ck3hkRHNdTpH0jB",
	"di40jIVyyx3UcXPKSxg2BhL/U1INlw5Exv5eLghf+Uf72j7flD18d+UeVDunStcYgSwoN/6BGFXaALL3",
	"nxwSqpyPw4O+TQ1t0+Iz1LD3iRm2vEGClhTuDEoa1zQrkVlp9pGgMqbVfu5mN6MaEvW83LuptDCRkqzq",
	"GdBOnt4PKnnGswfJwcVxoopJLGYeoIZfq2fczYtKiwR9hlXjjrDMQBqVyrVIyGJh0wyP0ZwyDVZCzclc",
	"i6rOyy11pg4eIsHndJFJiO2wSkn05wC94X/9/8FWllPL7VLRbRMzG10MkElXahrVt9PgM8r2FxYUM5Hx",
	"2DW37IbP2cSjWL2931qBI1NIKg1ce+pgN7MYTe4IZYYtvxh87YY3+316L8r5kE62m07vKAO1UhoSHOC3",
	"TESf61ihberNhWUygmsSWRDx7VBDJkZS+CSQSVvuap2qTqu1oHqZzZqRSFqGYqRuWusQjFfjYhxeTVB3",
	"NLCRkBBObCikhXUL6ughAx3tWr7HCE3U8ZQLjkr+FrFMaZAKCY5msCRsbjCp37toTvnEcEy3KWPiXqFu",
	"aFuJPCYydkEZCe52iVaIRFIoZdbmWK8ctDMaAVdQslc3JdES0KntWGyb6/7+vkns66aQi5Zfq1rng144",
	"vAobp812c6kTVupSluMnr93yuiAvJ8w5So2NvF+yDrBIgZOU4g5+1Ww3X/smiA2aFklp6+6EsHRJTlol",
	"NF5ATQoxiQURxnbuYpNB0D3VS4P7NG8qZ6kpGbFVQtqxQewlXRdcoNzw/7S76QV5oEmWIJ4lM5A+n1jg",
	"VsY9bJbJW/hfMrBtWn8JCXlw6UvRP2wTqOjb+34C7vzUrukWJ25L3Dlpt9sWIv1jtbW1DvbnxAOJsE7b",
	"UqItq7obppY5ura/vanTdjsPWeD20kiaMp+/Wr8r13XbyHs6vVr+YPGgrjZSea43tXtmWdU8Y2xlPO31",
	"QV1SKWYMkh9fppP7JlKjzoDfEUZjJF0rAZW8aB3gn76vKiZrEmZhAaT7zmFRPf904INn4/OaLCxjzkdu",
	"TPEj6ohbzyZFRBCH+32RtwcNjyuB54Rd54z7YORdpo7foIhR4DpnuxCbajJ3cKdIEw3miAud93HjYMrz",
	"HjJIdE8ZQwvgRhPDsdGg35zyKR+7nOf6S0cmmrvhqHFyenrcmfIGOmm8eYWiJZEksgjOBF+Y8StNpHZY",
	"QxAT9yAjogAxMOQFCYliuqDazDREn1COBGerykwVeFBRgeVcy1W6BK7MupDHTv5Gpps65c/5lLgT2fYj",
	"4sbF/tqSuhYfbES8FfHqL4YG5/zb30PXFUA6+Sa71jZqPGP8uyGR7WM5PX79fnpYGm28VpGciBJmmOcK",
	"wQNVrtv4+vT0+2m0afNuEfJYmEJAaKfW3xKuPeoWSFnF63VQT5/yjzX7WNQYdCa566cvtz6M5k1Sx+wq",
	"2H0G+v3ms+Y3ogDv8y9NFavlhJMqlH8B3TaZ/2LaW0L0uWQxL/GAwcrdImsuBrqmwOnbcUQ2f1WoZsHr",
	"XjXnuXX7cl6dMTZTWlt/P6khX6/39pDdMeqg6fX3c/W8KBUazU29+reMNX+xB2It2BtKloke8onZCu10",
	"wusC6xt5R/v7ZcJDrPx/DrftcGegDyK7/yhXT4s//LK/CC+K/Zb1Bi96z19LIgOUqHBFtSGMOQgHe6CF",
	"0TlEq4iB65RYAl0rKD/T+mb93wAAAP//8S0zJ2YnAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
